### ISSUE TITLE
Add subscriber count on page

### ISSUE THREAD

**Issue by zrthxn** [Beta-Persei/vaccination-slot-notifier#20]
A real-time counter to show how many people have signed up/subscribed. Helps to inspire confidence in skeptical people.
Could use a socket connection to update in real time or just render serverside if thats too much hassle.

**Comment by abbasidaniyal** [comment]
Yes that sounds nice. Can start with a static number and then use ws to make it dynamic.

**Comment by abbasidaniyal** [comment]
Closing for now. Will reopen when we move towards a ws based count
