### ISSUE TITLE
Don't register duplicate emails 

### ISSUE THREAD

**Issue by zrthxn** [Beta-Persei/vaccination-slot-notifier#40]
Check if email already exists, before creating subscriber.

**Comment by abbasidaniyal** [comment]
Yes, we can split the "Subscriber" model into two separate models. One "User" with the email / phone_number and the other for the pincode/districts subscriber with a fk mapping to "User".

**Comment by zrthxn** [comment]
But there will be two tables then and the existing data will have to be migrated. Better to stick with one only and check which properties (i.e. self.pincode or slef.district) exist and check acc to that.
